### ISSUE TITLE
Easy way to make `xmake run` work with dependent files/directories?

### ISSUE THREAD

**Issue by paul-reilly** [xmake-io/xmake#1054]
I might be missing something, but there doesn't seem to be a way at the Description Scope to copy files/dirs (or add dirs to the temp environment) so that a binary executed with `xmake run` can find them.

We have `target:add_installfiles`, but this is just for install.  We can implement a `before_build` step, but this seems to need to be in addition to `add_installfiles` or a custom install step.

It seems that something like:
```
target::add_depfiles("config.ini", "scripts/", "fonts/")
```
... or extending `target:add_installfiles` to work with `xmake run` should exist.

Adding dirs to the temp environment would perhaps be best for working with things like scripts.

**Comment by waruqi** [comment]
I think this is too customized. You should use os.cp to copy the files you need in after_build or before_run. This only requires a few lines of script.

Or you can use add_runenv to add the environment variables needed for running to point to the resource files of your source directory. Then you load your files through environment variables first in the program. This also avoids frequent copying of these files every time you compile and run.

**Comment by paul-reilly** [comment]
I don't think it's too specialized, most non-trivial programs have files they depend on and `xmake run` is a great feature which deserves something to maintain its simplicity.

In general when I think of other build systems, the build files can quickly turn from clean to quite messy when dealing with these housekeeping tasks. xmake could do this better. 

I tried with `add_runenv` but - and I don't know why I didn't think of this - code changes would be avoided with runtime symlinks/directory junctions. Maybe:

```
target:add_runlinks("config.ini", "scripts/", "fonts/", "data/" ... [, { prefixdir = "res" } ])
```

Which is a lot nicer than CMake:
```
add_custom_command(TARGET tests POST_BUILD
  COMMAND ${CMAKE_COMMAND} -E create_symlink
    ${CMAKE_CURRENT_SOURCE_DIR}/config.ini
    ${OUTPUT_DIR}/config.ini
  COMMENT "Creating symlink to config.ini at: ${OUTPUT_DIR}"
)```

Does `os.` have a command to create symlinks/junctions at the moment?

**Comment by waruqi** [comment]
> Does os. have a command to create symlinks/junctions at the moment?

os.ln("srcpath", "destpath")

The function of `before_run`/`after_build` is to let users more flexibility and customization. You can use `os.cp`/`os.ln` to do anything to simplify `xmake run` in these two stages.

```lua
target("test")
    before_run(function (target)
        local resdir = path.join(target:targetdir(), "res")
        if not os.isdir(resdir) then
            os.ln("config.ini", path.join(resdir, "config.ini"))
            os.ln("scripts", path.join(resdir, "scripts"))
            os.ln("fonts", path.join(resdir, "fonts"))
            os.ln("data", path.join(resdir, "data"))
        end
    end)
```

If you have a better resource dir to manage them uniformly, it will be easier.

```lua
target("test")
    before_run(function (target)
        local resdir = path.join(target:targetdir(), "res")
        if not os.exists(resdir) then
            os.ln("res", resdir)
        end
    end)
```

This is not very complicated, only a few lines of scripts are needed to complete the configuration.

Of course, I prefer to use `set_runenv` to point to and search for them directly.

```lua
target("test")
    set_runenv("RESOURCES_ROOT", "$(projectdir)/res")
```

Then we only need to load the resource file pointed to by $RESOURCES_ROOT first in the program, if it exists.

It is very clean and fast.

Therefore, I don’t want to implement too much logic in the built-in on_run, because the needs of each user are different. For example, I don’t like to copy files every time before the run. But users can implement it flexibly by himself in `before_run/after_build`.

**Comment by paul-reilly** [comment]
Thanks for the detailed reply, much appreciated! I won't bore you any more with this but I can't promise that I won't mention it again! :)
