### ISSUE TITLE
vsxmake project breaks with conditionnal targets

### ISSUE THREAD

**Issue by yamashi** [xmake-io/xmake#1275]
### Describe the bug
using:
```lua
if is_mode("debug") then 
    print("hello")
else
    target("test")
        ...
end
```
Will error out when generating the vsxmake (see below).

Note that building such a project works fine from the command line.

### Expected behavior
vsxmake project generates.

### Error output
https://pastebin.com/Ft4YaFLz

### Related Environment

Please provide compiling and running environment information:

- xmake version: 2.5.2
- os: Windows 10
- target platform: x64

**Comment by waruqi** [comment]
I will fix it, please wait ..

**Comment by waruqi** [comment]
> https://pastebin.com/Ft4YaFLz

I fixed this error (ld/ar errors) in the `vsxmake` branch, but vsxmake plugin still cannot support this feature. 

The target list of each compilation mode must be exactly the same, because in the vs project, no matter which mode is switched, the target subproject list will exist and will compile them. .

**Comment by waruqi** [comment]
I have merged it, you can try it.
