### ISSUE TITLE
absolute path of scriptdir

### ISSUE THREAD

**Issue by danieleTrimarchi** [xmake-io/xmake#1480]
```
task("printVariablePath")
	on_run(function()
		print("$(scriptdir)")
		print(path.absolute("$(scriptdir)"))
	end)
	set_menu {
                usage = "xmake printVariablePath"
            ,   description = "print variable path!"
	}
task_end()
```

The first print will return the abs path of the scriptdir (ie: "C:\prog\printtests") , while the second line (with path.absolute) will concatenate twice the abs path of the scriptdir (ie; "C:\prog\printtestsC:\prog\printtests")

Windows 10, xmake v2.5.4+202106020935

**Comment by waruqi** [comment]
The processing of built-in variables is done inside print, and path.absolute will not deal with it.

so `path.absolute("$(scriptdir)")` -> `C:\prog\printtests\$(scriptdir)`

 -> print: `"C:\prog\printtestsC:\prog\printtests"`

please use `os.scriptdir()` in script scope instead of `$(scriptdir)`.

`$(scriptdir)`  builtin variables are usually used in the description scope.
