### ISSUE TITLE
When building a Windows project in commandline and then with VS, everything is rebuilt

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#1824]
### Describe the bug
I noticed this behavior for the last year, when you build a project using xmake in commandline and then switch to a visual studio project, every file built in commandline has to be rebuilt in visual studio.

I did look at xmake internals to understand why xmake though files needed to be rebuilt and finally understood it, it comes from the additionnal `-FC` flag added by xmake when using VS.

From modules/core/tools/cl.ua:
```lua
    -- we need show full file path to goto error position if xmake is called in vstudio
    -- https://github.com/xmake-io/xmake/issues/1049
    if os.getenv("XMAKE_IN_VSTUDIO") then
        self:add("cxflags", "-FC")
    end
```
https://github.com/xmake-io/xmake/blob/f9af5b38ecf35c9e5741542e7a0f02f9dd0409f8/xmake/modules/core/tools/cl.lua#L37-L41

The problem is that -FC gets into depends depvalues, and as depvalues change between VS and commandline, xmake thinks file needs to be recompiled.

Maybe that flag should be added after checking depends? Or that depends should ignore some flags that won't affect object/errors/warnings generation (such as -FC).

### Expected behavior
That files don't get rebuild without change between commandline and VS.

### Related Environment

- xmake version: 2.5.9
- os: Windows 10
- target platform: Windows 10

**Comment by waruqi** [comment]
There is currently no better way to deal with it. If you want to dynamically ignore -FC during the compilation phase, this may affect compilation performance. Because every time you compile a file, you need to traverse to remove it.

There may also be some special hard-coded operations, which is not very good either.

A workaround solution is that you also set the XMAKE_IN_VSTUDIO variable in the global environment to ensure that the flags on both sides are consistent.
