### ISSUE TITLE
Optimal parallelization of targets for C++20 modules

### ISSUE THREAD

**Issue by ozankabak** [xmake-io/xmake#1862]
### Is your feature request related to a problem? Please describe.
@waruqi solved [dependency issues](https://github.com/xmake-io/xmake/issues/1858) in multi-target C++20 modules in [a recent fix](https://github.com/xmake-io/xmake/commit/12ee3ed6eb196f5d9e5cdeb619c40f51b2bec144). As he correctly points in the [comments](https://github.com/xmake-io/xmake/blob/12ee3ed6eb196f5d9e5cdeb619c40f51b2bec144/xmake/rules/c%2B%2B/modules/xmake.lua#L25), the current approach is over-conservative in disabling parallelism. In this issue, I am offering an approach that will build targets in parallel as much as possible while still obeying the dependency relations between targets.

### Describe the solution you'd like
I propose a simple four-phase approach:
1. Build a module-target dependency graph involving *only* module-targets (i.e. targets involving C++20 modules).
2. Run a modified topological sorting algorithm (like [the one here](https://stackoverflow.com/questions/56802797/digraph-parallel-ordering)) to identify module-targets that can be built in parallel.
3. Build module-targets in this order, parallelizing when possible.
4. Build the rest of the targets as before (in parallel).

If I'm not mistaken, this should enable xmake to exploit parallelism to the fullest even with C++20 modules! Happy to discuss further and fix/improve the approach.

**Comment by waruqi** [comment]
The problem now is not the dependency graph between targets. The dependency relationship between the entire targets has been built through add_deps.

The problem is that there are dependencies between the module's .mpp/.cpp source files.

At present, xmake has been able to do a good job of automatically scanning the dependencies between .mpp files in a single target, building a dependency graph, and maximizing parallel compilation.

For multiple targets, there are dependencies. If it is a normal cpp file, we can further optimize them, and firstly parallel all the cpp files of the target, and then execute the link one by one according to the dependency graph.

However, if a target contains c++ modules, then the problem is more complicated. We built the target's dependency graph in time, which is useless. We cannot compile all the .mpp/.cpp of target A and B in parallel. .

Therefore, although I currently disable the across_targets_in_parallel strategy, the .mpp/cpp file of target A and the .mpp/cpp file of target B can still be compiled in parallel. It's just that the .mpp/cpp files of target A+B cannot be put together to achieve parallel compilation.

Unless we can scan all the target's .mpp/.cpp source files and build a large overall dependency graph, we can analyze the dependencies between them in a more fine-grained manner, but this implementation will be very complicated.

**Comment by waruqi** [comment]
for example:

```
target A
  - a1.mpp, a2.mpp, a3.mpp ...
  - a1.cpp ...

target B
  - b1.mpp, b2.mpp, b3.mpp ...
  - b1.cpp ...
```

target A depend on target B

#### across_targets_in_parallel (on)

build parallel (a1.mpp, a2.mpp, ... b1.mpp, b2.mpp ...) -> link targets A/B (As parallel as possible)

#### across_targets_in_parallel (off)

build parallel (a1.mpp, a2.mpp) -> link target A -> build parallel (b1.mpp, b2.mpp ...) -> link targets B

**Comment by ozankabak** [comment]
In your example, the algorithm I'm proposing would do this:
1. Build (a1.mpp, a2.mpp, ...) in the order given by the compiler, parallelize only to the extent allowed by that order.
2. Build (b1.mpp, b2.mpp, ...) in the order given by the compiler, parallelize only to the extent allowed by that order.
3. Build all the non-module files (a1.cpp, a2.cpp, ..., b1.cpp, b2.cpp, ...) in parallel, link the targets.

**Comment by waruqi** [comment]
> 1, 2 
The current build strategy of xmake is what you describe. I don’t need to change anything.

> 3
It is not yet possible to support separate parallelization of .mpp and .cpp, they can only be compiled together in parallel.

**Comment by waruqi** [comment]
The current rule mechanism cannot further control the granularity of parallelism between targets, unless the custom rule and internal construction graph rules are improved. This is a bit complicated, and maybe there will be a better way to achieve it in the future.

**Comment by ozankabak** [comment]
> It is not yet possible to support separate parallelization of .mpp and .cpp between multiple targets, they can only be compiled together in parallel.

> And even if separate parallelism is supported, if target D has .mpp and also depends on targets A and B, then cross-parallel compilation must be disabled for target for .mpp. But this will also affect .cpp

OK, so that's basically the only difference between what I have in mind vs. what xmake actually currently does. I am proposing to build module files first (with limited parallelization respecting ordering), and then compiling the rest with full parallelization. Current xmake strategy seems to build module files and regular files in lockstep.

Thanks for the discussion!

**Comment by waruqi** [comment]
this patch https://github.com/xmake-io/xmake/pull/2641 will enable full parallel build for c++ modules.
