### ISSUE TITLE
XMake does not set toolchain kind to PATH

### ISSUE THREAD

**Issue by A2va** [xmake-io/xmake#3702]
### Xmake Version

v2.7.8+dev.76bfacb40

### Operating System Version and Architecture

Windows 11 22H2

### Describe Bug

Normally xmake is supposed to set PATH variable automatically for toolchain kind. 
To reproduce, you can install mingw and try setting it as a toolchain:
```
xrepo install llvm-mingw
xmake f --toolchain=mingw
```
As mingw is supposed to try to get the toolchain from the PATH
https://github.com/xmake-io/xmake/blob/21fb04a180feb12bb57677fc1e1638d185fb10f1/xmake/modules/detect/sdks/find_mingw.lua#L48-L62
If the llvm-mingw package appears in the PATH, xmake should resolve it correctly, but that did not happen.

To confirm that llvm-mingw is not present in the PATH, I also wrote a small script to display the PATH variable `print(os.getenv("PATH")`.
For reference, it displays this:
```
C:\Program Files\xmake;
C:\Program Files\Eclipse Adoptium\jdk-17.0.5.8-hotspot\bin;
C:\Program Files\Eclipse Adoptium\jdk-11.0.16.101-hotspot\bin;
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;
C:\Program Files\Git\cmd;C:\Program Files\CMake\bin;
C:\Program Files\nodejs\;
C:\Program Files\GitHub CLI\;C:\Program Files\gitui\bin\;
C:\WINDOWS\system32;C:\WINDOWS;
C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\WINDOWS\System32\OpenSSH\;
C:\Program Files\nu\bin\;
C:\Program Files\dotnet\;
C:\Users\leres\AppData\Local\Programs\Python\Python310\Scripts\;
C:\Users\leres\AppData\Local\Programs\Python\Python310\;
C:\Users\leres\.cargo\bin;C:\Users\leres\AppData\Local\Microsoft\WindowsApps;
C:\Users\leres\AppData\Local\Programs\Microsoft VS Code\bin;
C:\Users\leres\AppData\Local\GitHubDesktop\bin;
C:\Users\leres\vcpkg;C:\Users\leres\.dotnet\tools;C:\Users\leres\AppData\Roaming\npm
```

### Expected Behavior

XMake is supposed to set the PATH env for a package that which is a toolchain kind

**Comment by waruqi** [comment]
> ```
> xrepo install llvm-mingw
> xmake f --toolchain=mingw
> ```

The llvm-mingw package and the mingw toolchain are completely different things and they have nothing to do with each other.

The mingw packages are llvm-mingw, mingw-w64, and the mingw toolchain can be used without these packages and just use the mingw toolchain from the system installation path, e.g. /mingw64 for msys2, /usr/local/opt/mingw-w64 for macOS. it is usually necessary to switch to the mingw platform. and set the mingw path to `xmake f -p mingw --mingw=/xxx`, rather than just switching toolchains.

If you want to associate the mingw toolchain with the llvm-mingw package, this is also possible. You need to introduce the package using add_requires("llvm-mingw") and associate the package with the toolchain using `set_toolchains("mingw@llvm-mingw")` to enable automatic toolchain downloads. See the full example at https://github.com/xmake-io/xmake/blob/master/tests/projects/package/toolchain_llvm_mingw/xmake.lua

Of course, you can also associate the mingw-w64 package instead of llvm-mingw.

**Comment by A2va** [comment]
Thank you for your explanation, I understand better now. But the problem is that it is the same regardless of the toolchain installed. I tried to install mingw-w64 as well but like llvm-mingw it doesn't show up in the PATH.

**Comment by waruqi** [comment]
> Thank you for your explanation, I understand better now. But the problem is that it is the same regardless of the toolchain installed. I tried to install mingw-w64 as well but like llvm-mingw it doesn't show up in the PATH.

Installing any package does not modify the system PATH, only the environment variables set by the target can be retrieved from the various script fields in the target's before_build/after_link etc. if they are associated with the target using add_packages.

```lua
add_requires("xxx")
target("test")
    add_packages("xxx")
    after_build(fucntion (target)
        print(os.getenv("PATH"))
    end)
```

If you use `set_toolchains("mingw@llvm-mingw")`, it will associate the package to the toolchain and let xmake automatically use the mingw binary provided by the llvm-mingw package to compile the specified target

**Comment by waruqi** [comment]
If you want to set llvm-mingw package to system PATH, you can use `xrepo` virtual environments. https://xrepo.xmake.io/#/getting_started?id=package-virtual-environment

```bash
$ xrepo env -b llvm-mingw shell
echo %PATH%
```

**Comment by A2va** [comment]
Sorry, I made an issue for not much. I was confused, I tought that the toolchain kind added to the system PATH. Again thanks for your explainations and advices.
I will close the issue, since it's resolved.
