### ISSUE TITLE
A small fix to support SSE4.2 and AVX-512

### ISSUE THREAD

**Issue by ruiyuanlu** [xmake-io/xmake#3786]
### Is your feature request related to a problem? Please describe.

SSE 4.2 not enabled properly for windows VS2019+. AVX-512 not supported.

```lua
add_vectorexts("mmx")
add_vectorexts("neon")
add_vectorexts("avx", "avx2")
add_vectorexts("sse", "sse2", "sse3", "ssse3")
```

this could not enable sse and avx512 on msvc even if sse4.2 is available.

![image](https://github.com/xmake-io/xmake/assets/16774189/fd1318a5-6b5b-419a-af0c-145134e191e5)

### Describe the solution you'd like

Support SSE4.2 on windows VS2019+, and support AVX-512 by `add_vectorexts ` api like:

```lua
add_cxflags("sse4.2", "avx512")
```

### Describe alternatives you've considered

```lua
add_cxflags("/d2archSSE42")  -- For msvc SSE4.2, the only undocumented way works
add_cxflags("arch:AVX512")    -- for msvc 2019+ avx512 support
```

![image](https://github.com/xmake-io/xmake/assets/16774189/db69e748-8846-48db-9298-ef06aa3cc8f2)

See reference:
[AVX-512 for VS2019+](https://learn.microsoft.com/en-us/cpp/build/reference/arch-x64?view=msvc-170&viewFallbackFrom=vs-2019)

[SSE4.2 for VS](https://stackoverflow.com/questions/64053597/how-do-i-enable-sse4-1-and-sse3-but-not-avx-in-msvc)

**Comment by waruqi** [comment]
Adding new abstracted values requires support for at least both msvc and gcc/clang.

But for gcc there is currently no easier way to set avx 512.

-mavx512f -mavx512dq -mavx512bw -mavx512vl ...? 

https://github.com/xmake-io/xmake/issues/1613

If you know how to set it up better, you can just open a pr to improve them.

**Comment by 2283572185** [comment]
To some degree, maybe we can design a new option `cpu_arch`. Sometimes we need not only simd support but also other extended instruction sets like bmi and bmi2.We can set `native` to the option `cpu_arch` for default. For msvc, we may map the `cpu_arch` to  specific instruction sets. When it comes to `native`, we may use the intrinsic function `_may_i_use_cpu_feature` in the C code of xmake core to check the instruction sets that the cpu supports. The arch name should in gnu format like znver4 so that it can be passes to gcc/clang directly.

**Comment by waruqi** [comment]
I added it, try it again.

```lua
add_vectorexts("sse4.2", "avx512")
```

```
xmake update -s github:xmake-io/xmake#avx512
```
