### ISSUE TITLE
feature: possible typescript support?

### ISSUE THREAD

**Issue by std-microblock** [xmake-io/xmake#5836]
### Is your feature request related to a problem? Please describe.

It's always weird and annoying for me to write lua. Is it possible to also support typescript as an alternative?

### Describe the solution you'd like

Bundle https://github.com/TypeScriptToLua/TypeScriptToLua into a single-file javascript, and use quickjs-ng to to evaluate the script to transpile the typescript into lua before executing.

If the way can be accepted, I can make a pull request in the near future.

**Comment by std-microblock** [comment]
The main concern is that this might increase the binary size for around 400k, I guess. If the binary size matters, we can make it an opt-in feature

**Comment by std-microblock** [comment]
for the following xmake.lua:
```lua
add_rules("mode.debug", "mode.release")

target("console")
    set_kind("binary")
    add_files("src/*.c")
    if is_mode("debug") then
        add_defines("DEBUG")
    end```

the equivalent xmake.ts can be something like:

```typescript
add_rules("mode.debug", "mode.release")

target('console')(console => {
    console.kind = 'binary'
    console.add_files(...)
    if(is_mode(...)) console.add_defines(...)
})```

the syntax can be discussed later after the basic transpile implementation is completed.

**Comment by waruqi** [comment]
Currently, we do not consider other languages ​​as built-in configuration. However, you can write a tool to convert ts to lua, and then call the xmake command. For example: xmake-ts

**Comment by std-microblock** [comment]
May I ask the reason? TS support wouldn't increase the complexity of maintenance of other component.

**Comment by std-microblock** [comment]
However, if I want to fully integrate with the xmake ecosystem, the best way is to make it an official function. SoiI don't want to create a third-party repo for the support

**Comment by waruqi** [comment]
> May I ask the reason? TS support wouldn't increase the complexity of maintenance of other component.

### Binary size and Reduce third-party libraries

xmake needs to introduce as few third-party dependencies as possible to keep it lightweight and cross-platform. Especially the introduction of dependencies on core binary. Too many third-party dependencies will also make packaging very difficult, such as debian/archlinux and other distribution packages.

Currently xmake has introduced lua-cjson, lz4, tbox, sv, xxhash and other dependencies. In order to package xmake into debian. Several of its dependent libraries, such as tbox, sv, etc., took us several years to successfully push into debian.

In the future, I will try to implement cjson, semver, hash myself to reduce third-party dependencies as much as possible. And ensure that the binary is as small as possible.

> might increase the binary size for around 400k

This is unacceptable to us. In addition, I am not sure whether quickjs-ng has been included in all distributions, otherwise it will affect the packaging of xmake.

### Configuration consistency

We need to keep the configuration style as simple and consistent as possible. 

Therefore, we will only consider one language(Lua) 

Too many different types of language configurations will only make the configuration style confusing and make it more difficult for new users to get started.

### Increased maintenance workload

In addition, it will also make xmake's own projects and documents more difficult to maintain, increasing our maintenance workload.

### Other reason 

I don't like ts/js

**Comment by std-microblock** [comment]
> In addition, I am not sure whether quickjs-ng has been included in all distributions, otherwise it will affect the packaging of xmake.

As a popular embedding framework, quickjs is already available on nearly all platforms. It even (and is designed to) runs on embedding platforms so this shouldn't be a concern.

> In addition, it will also make xmake's own projects and documents more difficult to maintain, increasing our maintenance workload

We can keep the consistency between TS and Lua api (this can be done automatically), thus the document wouldn't have to be maintained separately for the TS part.

> might increase the binary size for around 400k
I checked again and found that the size can be reduced to about 100k.

> We need to keep the configuration style as simple and consistent as possible.

The style can be the same if you'd like to. We can just use TS syntax and keep xmake dsl in mind.

> I don't like ts/js

It's not JavaScript, it's lua with the syntax from TypeScript.

> make it more difficult for new users to get started.

There's also many people who dislikes lua. If we support typescript, more of them can benefit from xmake.

**Comment by std-microblock** [comment]
If we cannot make it directly into xmake, is it acceptable to release it as a package in xmake repo, which done the conversation? Then we can do something like this:

// xmake.lua
add_requires("xmake-ts")

// xmake.ts
target('xxx') ....

**Comment by std-microblock** [comment]
Also would the xmake repo accept code generated from xmake-ts?

**Comment by qudix** [comment]
> There's also many people who dislikes lua. If we support typescript, more of them can benefit from xmake.

I'm sorry if this sounds harsh, but then they should look elsewhere or get over it. You shouldn't use, or not use, a tool *just* for it's language choice, but whether it fits your project's needs. You are of course free to make a third-party transpiler or any plugin, nobody can stop you, but I don't think you can expect official support beyond questions or resolving technical issues in xmake itself.

**Comment by std-microblock** [comment]
> > There's also many people who dislikes lua. If we support typescript, more of them can benefit from xmake.
> 
> I'm sorry if this sounds harsh, but then they should look elsewhere or get over it. You shouldn't use, or not use, a tool _just_ for it's language choice, but whether it fits your project's needs. You are of course free to make a third-party transpiler or any plugin, nobody can stop you, but I don't think you can expect official support beyond questions or resolving technical issues in xmake itself.

Well that's okay. You can see that I'm using xmake despite I dislike xmake, so it's not "based on languaged choice."

As I don't want to make our conversation a quarrel, and knowing that you personally dislike TS, I've abandoned the idea of implementing it in xmake core. I'll make it a separate project then.

**Comment by SirLynix** [comment]
I can't find it but there's an issue about allowing to use xmake with a simple yaml file for simple projects (similar to Cargo), and as far as I remember someone created a plugin for that, I guess the same is possible for typescript.

However it wouldn't be part of xmake core and xmake-repo, as it would fracture the xmake ecosystem and cause more harm than good.
