### ISSUE TITLE
Support independent working/build directory

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#820]
If we do not want to create .xmake and build directories under the current project directory, and keep the project directory clean.

We can try run:

```console
$ mkdir /xxx/working; cd /xxx/working

# We manually create an empty .xmake directory and 
# specify the current directory as the working and build directory
$ mkdir .xmake

$ xmake -P /xxxx/myproject
```

It will generate build and .xmake dirs to `/xxx/working`

If we only want to move projectdir/.xmake to build/.xmake, we can run 

```console
$ cd projectdir
$ mkdir build; cd build

# We manually create an empty .xmake directory and 
# specify the current directory as the working and build directory
# mkdir .xmake

$ xmake -P ..
```

Or we can uses environment vars to set these dirs.

```console
$ export XMAKE_CONFIGDIR = /xxx/working
$ cd projectdir
$ xmake f --buildir=/xxx/working/build
$ xmake
```

**Comment by waruqi** [comment]
done, `xmake update -s dev`

**Comment by davidchisnall** [comment]
The requirement to create .xmake in the directory is annoying.  The normal idiom for building is:

 - Create build directory.
 - Change to the build directory.
 - Run the build tool, pointed at the source directory.

With xmake, this sequence *appears* to work but actually scatters files in my source directory.  In secure build environments, the source directory is mounted read-only and so something that looks as if it's working will then fail.  This makes it harder for me to convince other people to try xmake, because their normal workflow requires extra steps and has annoying failure modes.

**Comment by davidchisnall** [comment]
It looks as if you need to specify `-o $(pwd)` while doing the configure step as well to actually get the expected behaviour (all build state is in the build directory).  

It's unfortunate that xmake defaults to trying to build from the source directory.

**Comment by waruqi** [comment]
> It looks as if you need to specify `-o $(pwd)` while doing the configure step as well to actually get the expected behaviour (all build state is in the build directory).
> 
> It's unfortunate that xmake defaults to trying to build from the source directory.

If you're already in the build directory, you don't need to specify `-o `

**Comment by waruqi** [comment]
> It looks as if you need to specify `-o $(pwd)` while doing the configure step as well to actually get the expected behaviour (all build state is in the build directory).
> 
> It's unfortunate that xmake defaults to trying to build from the source directory.

If you're already in the build directory, you don't need to specify `-o `

**Comment by davidchisnall** [comment]
> If you're already in the build directory, you don't need to specify -o

I agree that this should be the behaviour, however when I don't specify -o it creates a build directory in my source tree and puts object files there.  When I do, it creates them in the current directory.

My exact sequence:

```
$ cd build
$ mkdir {my project and build config name}
$ cd {my project and build config name}
$ mkdir .xmake
$ xmake f -P ~/{my project name} --{configuration args}
$ xmake -P ~/{my project name}
```

The build files are created under `~/{my project name}/build/.objs`, not in my build directory.  If I specify `-o $(pwd)`, then the build files are created in the build directory.  The paths are slightly confusing, because it appears that xmake runs the compiler from the source directory and provides it with a relative path to the build directory, rather than running it in the build directory and providing it with an absolute path to the source directory, but the end result is correct.

**Comment by waruqi** [comment]
I have improved it, try it again. `xmake update dev`

**Comment by davidchisnall** [comment]
I have built from source.  If I run `xmake update dev`, it complains that I don't have unzip or 7zip installed (`unzip` is in the FreeBSD base system, so I do have it), not sure what it's trying to do.  I've updated the git repo and submodules and I don't see any changes in the commit history that I'd expect to address this.  Can you link to the commit with the improvements so that I can make sure that I have it?

**Comment by SirLynix** [comment]
The error message is a bit misleading as you need both actually (or at least 7zip).

The change is on the dev branch: https://github.com/xmake-io/xmake/commit/e59566a7d6f7ce12b1f132b335a8788b8050e8ae

**Comment by davidchisnall** [comment]
Thanks, I can confirm that this works if I move to the dev branch.
