### ISSUE TITLE
setting config value erases existing config values

### ISSUE THREAD

**Issue by caizongchao** [xmake-io/xmake#823]
xmake 2.3.3

xmake erases existing config value while setting new config value, for example:

xmake f -m debug
xmake f -o c:\temp

I expect that both -m and -o config values are set, but in fact only -o config value exists.

Is this behavior by design?

thanks.

**Comment by waruqi** [comment]
yes, xmake does not support incremental configuration, requiring a full configuration each time.

you need run 

```console
xmake f -m debug -o c:\temp
```

**Comment by caizongchao** [comment]
It will be very inconvenient when project contains a lot of options. For example, I would have to specify a lot of options like "--some-option1=y --some-option2=n ..." when what I want to do is simply testing between debug and release build with "xmake f -m debug/release".

As a workaround I have to directly edit .xmake/.../cache/config to change config values.

**Comment by waruqi** [comment]
Because the incremental configuration will be troublesome to deal with the dependencies between configuration options, it is easy to cause some invalid configuration value combinations. 

I have tried to support it before, but it will bring more problems to be solved, such as automatic synchronization of dependencies between configurations.

for example:

```console
xmake f -p macosx -a x86_64 
xmake f -p android  #<---  we need change arch to (armv7-a, arm64) automatically, x86_64 will be invalid
```

Many other configuration parameters need to consider synchronization.

Therefore, I would rather directly complete the configuration to simplify the configuration process and avoid various problems

You can use `xmake macro` plugin to simplify configration or use shell script. https://xmake.io/#/plugin/builtin_plugins?id=macros-recording-and-playback

At present, I don't plan to modify the configuration mode. For example, ./configure/cmake is only fully configured.
