### ISSUE TITLE
ninja rules not conceived from custom toolchain

### ISSUE THREAD

**Issue by n8v8R** [xmake-io/xmake#916]
### Describe the bug
ninja rules are not being conceived from from custom toolchain, likely as xmake not recognising such. Subsequent wondering whether xmake is even utilising those binaries on its own.

### Expected behavior
ninja rules being conceived, and utilised by xmake, from custom toolchain

### Error output
there is no error output but just a lack of ninja rules

### Related Environment

Please provide compiling and running environment information:

- xmake version: v2.3.6+202008021551 **dev**
- os: linux/x86_64

### Additional context
1. with this custom toolchain

```
toolchain ("my_llvm")
  set_kind  ("standalone")
  set_toolset ("cc", "clang-10")       
  set_toolset ("cxx", "clang++-10")               
  set_toolset ("as", "clang-10")                  
  set_toolset ("ar", "llvm-ar-10")                
  set_toolset ("ld", "ld.lld-10")                 
  set_toolset ("mm", "clang-10")                  
  set_toolset ("mxx", "clang++-10")               
  set_toolset ("sh", "ld.lld-10")                 
  set_toolset ("strip" , "llvm-strip-10")         

  add_defines ("my_llvm")
toolchain_end()
```
ninja rules for `ld` & `sh` & `strip` not being conceived.

N.B. _ld.lld-10_ is the linker binary (actually it symlinks to /usr/lib/llvm-10/bin/ld.lld) provided from LLD (https://lld.llvm.org/design.html | https://lld.llvm.org/index.html)

As _clang_ is only a compiler and not a linker and on its own leverages only the standard systemlinker _lld_ needs to be be specified instead.
___
2. changing in the custom toolchain

```
- set_toolset ("ld", "ld.lld-10")
+ set_toolset ("ld", "clang++-10")
```
then a ninja rule for `ld` is being conceived, similar when changing `sh` in the toolchain. Still leaves `strip` rule not being conceived.
___
Somehow it seems that _xmake_ does not recognise/acknowledge as valid the binaries:

* llvm-strip-10
* ld.lld-10

and discards them from conceiving ninja rules. Since this happens it raises the question whether _xmake_ in its processing also discards them or whether the issue is limited to conceiving the ninja rules.

**Comment by waruqi** [comment]
> ninja rules for ld & sh & strip not being conceived.
> 
> N.B. ld.lld-10 is the linker binary (actually it symlinks to /usr/lib/llvm-10/bin/ld.lld) provided from LLD (https://lld.llvm.org/design.html | https://lld.llvm.org/index.html)
> 
> As clang is only a compiler and not a linker and on its own leverages only the standard systemlinker lld needs to be be specified instead.

I know this, but for xmake, we will try to use clang++ as ld. Although clang++ is just a compiler front end, it will also call the real ld internally to link the program. The advantage of using ld is that we don’t need additional configuration. e.g. libc++, crt.o and other additional compiler library links and search paths will be handled automatically by clang++, which is more reliable, less error-prone, and convenient for us and your configuration process.

If you use lld directly, you may need add -lc++ -L/clang/lib and etc .. manually. 

Therefore, for xmake, we use g++ and clang++ as ld first. If it is only a c program, you can also use gcc/clang directly. Usually we don't directly pass ld/lld to `ld` config. If you want to modify the internal ld program, you can set `-fuse-ld=lld` to clang++

> then a ninja rule for ld is being conceived, similar when changing sh in the toolchain. Still leaves strip rule not being conceived.

The default release rule `add_rules("mode.release")` is configured with `set_strip("all")`, it will automatically use `clang -s` to strip the program, it has the same effect as using strip independently, so usually we will not call the strip command extra.

Only the mode.releasedbg rule will additionally call strip because it will also generate additional symbol files.

However, rules and custom scripts only support direct compilation and run mode `xmake build`, and plugins generated by projects (`xmake project -k ninja/cmake/make ..`) are not supported.

Usually, we would recommend that users run the xmake command directly to compile the program instead of generating third-party project files. This is not our main feature.

**Comment by n8v8R** [comment]
Thank for the valuable feedback. I would thus adjust the custom toolchain to 

```
toolchain ("my_llvm")
  set_kind  ("standalone")
  set_toolset ("cc", "clang-10")
  set_toolset ("cxx", "clang++-10")
  set_toolset ("as", "clang-10")
  set_toolset ("ar", "llvm-ar-10")
  set_toolset ("ld", "clang++-10")
  set_toolset ("mm", "clang-10")
  set_toolset ("mxx", "clang++-10")
  set_toolset ("sh", "clang++-10")
  set_toolset ("strip" , "llvm-strip-10")

  add_defines ("my_llvm")

  on_load(function (toolchain)
    toolchain:add ("ldflags", "-fuse-ld=lld, -stdlib=libc++")
    toolchain:add ("shflags", "-fuse-ld=lld, -stdlib=libc++")
    
toolchain_end()
```

Would that be the way to go?
